### ISSUE TITLE
Some questions about Inference

### ISSUE THREAD

**Issue by Senmo996** [XinyuXia97/UCMFH#4]
Hello, thanks for your paper and code!
And I wonder if I only have a text query like "a bald man", what should I do to retrieval images as I see the multi-modal transformer encoder's input is cat[image, text], but now I only have text?

**Comment by XinyuXia97** [comment]
Please note: This is cross-modal retrieval, not single-modal retrieval.
You can create a collection by pairing an equal number of text queries with image modalities from the database. For instance, [[img0, txt0], [img1, txt0], [img2, txt0], ..., [imgN, txt0]]. These pairs will undergo a multi-modal transformer encoder with vector concatenation.

**Comment by Senmo996** [comment]
Tks! I'll try it later!

**Comment by Leng-Lin** [comment]
> Please note: This is cross-modal retrieval, not single-modal retrieval. You can create a collection by pairing an equal number of text queries with image modalities from the database. For instance, [[img0, txt0], [img1, txt0], [img2, txt0], ..., [imgN, txt0]]. These pairs will undergo a multi-modal transformer encoder with vector concatenation.

Hello,Thank you for your answer to the question4，but I still have some questions，Could you help me solve my confusion？
 If i have trained the model，when i have a text，I want to ues the text to get images which match the text，how should i do？ 
In my opinion，cross-modal retrieval  task，for example， given a modal instance，I can ues it to get the instances of other modal，but refer to your code，i don't understand how to finish this task. Because when evaluate , the multi-modal transformer encoder need image-text pairs to generate encoded image and text feature，if i only give text，how should i put it into the multi-modal transformer encoder ?
Refer to your answer to Senmo996， if i put [[img0, txt0], [img1, txt0], [img2, txt0], ..., [imgN, txt0]] into a multi-modal transformer encoder， and i  have the out puts.  For image, it is easy to get the hash code, but which one  of the txt0s is the one i need to generate hash code？

**Comment by Leng-Lin** [comment]
> Please note: This is cross-modal retrieval, not single-modal retrieval. You can create a collection by pairing an equal number of text queries with image modalities from the database. For instance, [[img0, txt0], [img1, txt0], [img2, txt0], ..., [imgN, txt0]]. These pairs will undergo a multi-modal transformer encoder with vector concatenation.

Hello,Thank you for your answer to the question4，but I still have some questions，Could you help me solve my confusion？
If i have trained the model，when i have a text，I want to ues the text to get images which match the text，how should i do？
In my opinion，cross-modal retrieval task，for example， given a modal instance，I can ues it to get the instances of the other modal，but refer to your code，i can't understand how to finish this task. Because when evaluate , the multi-modal transformer encoder needs image-text pairs to generate encoded image and text feature，if i only give text，how should i put it into the multi-modal transformer encoder ?
Refer to your answer to Senmo996， if i put [[img0, txt0], [img1, txt0], [img2, txt0], ..., [imgN, txt0]] into a multi-modal transformer encoder， and i have the out puts. For image, it is easy to get the hash code, but which one of the txt0s is the one i need to generate hash code？
